export const ERROR_CODES = [
  'INVALID_FIREBASE_TOKEN',
  'USER_NOT_INVITED',
  'REFRESH_TOKEN_INVALID',
  'ORGANIZATION_CONTEXT_MISSING',
  'NOT_A_MEMBER',
  'FORBIDDEN_ROLE',
  'NOT_ASSIGNEE',
  'MEMBERSHIP_EXISTS',
  'PROJECT_NOT_FOUND',
  'INVALID_ASSIGNEE',
  'INVALID_TRANSITION',
  'VALIDATION_ERROR',
  'INTERNAL_ERROR',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const STATUS_BY_CODE: Record<ErrorCode, number> = {
  INVALID_FIREBASE_TOKEN: 401,
  USER_NOT_INVITED: 403,
  REFRESH_TOKEN_INVALID: 401,
  ORGANIZATION_CONTEXT_MISSING: 400,
  NOT_A_MEMBER: 403,
  FORBIDDEN_ROLE: 403,
  NOT_ASSIGNEE: 403,
  MEMBERSHIP_EXISTS: 409,
  PROJECT_NOT_FOUND: 404,
  INVALID_ASSIGNEE: 422,
  INVALID_TRANSITION: 422,
  VALIDATION_ERROR: 422,
  INTERNAL_ERROR: 500,
};
